checks:
  javascript: true
build:
  nodes:
    analysis:
      tests:
        override:
          - js-scrutinizer-run
    coverage:
      tests:
        override:
          -
            command: 'yarn test --coverage'
            coverage:
              file: 'coverage/clover.xml'
              format: clover
